skillMetadata:
  sections:
    - name: Location Updates
      fields:
        - name: use_geolocation
          type: bool
          label: Automatically Set Location by IP Address
          value: false
